#!/bin/sh
# adbd
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
start() {
    printf "adbd"
    /usr/bin/adbd &
}

stop() {
    printf "stop:\n"
}

restart() {
    stop
    start
}

case   "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
*)

    echo "Usage: $0   {start|stop|restart}"
    exit 1
esac

